image: node:latest


stages:
    - install
    - validate
    - build
    - deploy

install:
    stage: install
    script:
        - npm i
    artifacts:
        paths:
            - node_modules/

test:
    stage: validate
    script:
        - npm run test

lint:
    stage: validate
    script:
        - npm run lint

prettier:
    stage: validate
    script:
        - npm run prettier

build:
    stage: build
    script:
        - npm run build
    rules:
        - if: '$CI_COMMIT_REF_NAME == "main"'
          when: on_success
          allow_failure: true
    artifacts:
        paths:
            - out/

deploy:
    stage: deploy
    dependencies:
        - build
    script:
        - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
    rules:
        - if: '$CI_COMMIT_REF_NAME == "main"'
          when: on_success
          allow_failure: true

